### DISCUSSION TITLE
Why does DB initialization keep failing due to OOM (Out Of Memory)?

### DISCUSSION THREAD

**Discussion by seowon-lee** [mr-karan/logchef#35] [Q&A]
I'm trying to deploy LogChef as a pod on Kubernetes, but I'm consistently encountering failures during SQLite initialization

Here are the logs from the pod:
```
{"time":"2025-05-15T12:17:00.782072187Z","level":"INFO","source":{"function":"main.main","file":"/home/karan/Code/Personal/logchef/cmd/server/main.go","line":24},"msg":"starting logchef","buildInfo":"v0.1.0-alpha.4 (e92a129e 2025-04-25T11:20:54Z, linux/amd64)"}
{"time":"2025-05-15T12:17:00.782649387Z","level":"ERROR","source":{"function":"github.com/mr-karan/logchef/internal/sqlite.New","file":"/home/karan/Code/Personal/logchef/internal/sqlite/sqlite.go","line":66},"msg":"failed to set pragmas on main database","component":"sqlite","error":"error setting pragma \"PRAGMA busy_timeout = 5000\": unable to open database file: out of memory (14)"}
{"time":"2025-05-15T12:17:00.782679547Z","level":"DEBUG","source":{"function":"github.com/mr-karan/logchef/internal/sqlite.New.func1","file":"/home/karan/Code/Personal/logchef/internal/sqlite/sqlite.go","line":53},"msg":"closing main database due to initialization error","component":"sqlite"}
{"time":"2025-05-15T12:17:00.782689747Z","level":"ERROR","source":{"function":"github.com/mr-karan/logchef/internal/app.Run","file":"/home/karan/Code/Personal/logchef/internal/app/run.go","line":25},"msg":"failed to initialize application","error":"failed to initialize sqlite: error setting pragmas on main database: error setting pragma \"PRAGMA busy_timeout = 5000\": unable to open database file: out of memory (14)"}
{"time":"2025-05-15T12:17:00.782696445Z","level":"ERROR","source":{"function":"main.main","file":"/home/karan/Code/Personal/logchef/cmd/server/main.go","line":32},"msg":"application error","error":"failed to initialize sqlite: error setting pragmas on main database: error setting pragma \"PRAGMA busy_timeout = 5000\": unable to open database file: out of memory (14)"}
```

config.toml:
```
...
    [sqlite]
    path = "/data/local.db"
...
[auth]
admin_emails = ["admin@logchef.internal"]
session_duration = "24h"
max_concurrent_sessions = 1
...
```

deployment.yaml:
```
...
    spec:
      containers:
        - name: logchef
          image: "mrkaran/logchef:v0.1.0-rc.1-amd64"
          imagePullPolicy: IfNotPresent
          ports:
            - name: logchef
              containerPort: 8125
          volumeMounts:
            - name: config
              mountPath: /etc/logchef/config.toml
              subPath: config.toml
              readOnly: true
            - name: data
              mountPath: /data
          resources:
            requests:
              cpu: 1000m
              memory: 4Gi
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-data
```

pod describe:
```
...
Containers:
  logchef:
    Container ID:   containerd://cb...8144bc
    Image:          mrkaran/logchef:v0.1.0-rc.1-amd64
    Image ID:       docker.io/mrkaran/logchef@sha256:98c05f3e...7012aa0f4c
    Port:           8125/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      ...
      Finished:     ...
    Ready:          False
    Restart Count:  5
    Requests:
      cpu:        1
      memory:     4Gi
    Environment:  <none>
    Mounts:
      /data from data (rw)
      /etc/logchef/config.toml from config (ro,path="config.toml")
...
```
